Repository andryak/usi-hackathon-2019, pull requests merged in 2019-11, with the labels that each got.

#1 Setup React project
  .gitignore
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/serviceWorker.js
  yarn.lock
Labels: enhancement

#21 Write project description and guide for building/running
  README.md
Labels: documentation

#34 Add origin and destination SearchBoxes and directions
  package.json
  src/App.js
  src/components/map/Map.js
  src/components/sidebar/Sidebar.js
  src/utils/addGoogleSearchBox.js
  src/utils/directionPositions.js
  src/utils/getCurrentPosition.js
  yarn.lock
Labels: task
